# Generated by Django 5.2.14 on 2026-05-18 19:06

import common.validators.injury_tags
import common.validators.workout_days
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_injuryrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injuryrecord',
            name='banned_movement_tags',
            field=models.JSONField(default=list, help_text='List of restricted movement tags', validators=[common.validators.injury_tags.validate_injury_tags]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_workout_days',
            field=models.JSONField(default=list, help_text='List of workout days', validators=[common.validators.workout_days.validate_workout_days]),
        ),
    ]
