# Generated by Django 5.2.14 on 2026-05-17 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_gyms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GymEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_type', models.CharField(choices=[('barbell', 'Barbell'), ('dumbbells', 'Dumbbells'), ('bench', 'Bench'), ('squat_rack', 'Squat Rack'), ('smith_machine', 'Smith Machine'), ('cables', 'Cables'), ('pullup_bar', 'Pull-up Bar'), ('machine', 'Machine'), ('bodyweight', 'Bodyweight'), ('kettlebell', 'Kettlebell'), ('cardio_machine', 'Cardio Machine'), ('bands', 'Bands')], max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='gyms.gym')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
