# Generated by Django 5.2.14 on 2026-05-18 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buddy', '0001_initial'),
        ('gyms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='buddypair',
            constraint=models.CheckConstraint(condition=models.Q(('joined_user__isnull', True), models.Q(('host_user', models.F('joined_user')), _negated=True), _connector='OR'), name='buddy_pair_host_and_joined_user_different'),
        ),
    ]
