# Generated by Django 5.2.14 on 2026-05-17 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buddy', '0001_initial'),
        ('gyms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('primary_muscle', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('biceps', 'Biceps'), ('triceps', 'Triceps'), ('forearms', 'Forearms'), ('legs', 'Legs'), ('glutes', 'Glutes'), ('hamstrings', 'Hamstrings'), ('calves', 'Calves'), ('core', 'Core'), ('full_body', 'Full Body'), ('cardio', 'Cardio')], max_length=50)),
                ('secondary_muscles', models.JSONField(default=list)),
                ('equipment_type', models.CharField(choices=[('barbell', 'Barbell'), ('dumbbells', 'Dumbbells'), ('bench', 'Bench'), ('squat_rack', 'Squat Rack'), ('smith_machine', 'Smith Machine'), ('cables', 'Cables'), ('pullup_bar', 'Pull-up Bar'), ('machine', 'Machine'), ('bodyweight', 'Bodyweight'), ('kettlebell', 'Kettlebell'), ('cardio_machine', 'Cardio Machine'), ('bands', 'Bands')], max_length=50)),
                ('movement_pattern', models.CharField(choices=[('horizontal_push', 'Horizontal Push'), ('vertical_push', 'Vertical Push'), ('horizontal_pull', 'Horizontal Pull'), ('vertical_pull', 'Vertical Pull'), ('squat', 'Squat'), ('hip_hinge', 'Hip Hinge'), ('lunge', 'Lunge'), ('core', 'Core'), ('carry', 'Carry'), ('rotation', 'Rotation'), ('cardio', 'Cardio'), ('isolation', 'Isolation')], max_length=50)),
                ('injury_risk', models.JSONField(default=dict, help_text='Joint risk mapping')),
                ('movement_tags', models.JSONField(default=list)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('unilateral_or_bilateral', models.CharField(max_length=20)),
                ('estimated_station_time_minutes', models.PositiveIntegerField()),
                ('default_sets', models.PositiveIntegerField()),
                ('default_rep_range', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SharedWorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommended_split', models.CharField(choices=[('full_body', 'Full Body'), ('upper_lower', 'Upper Lower'), ('push_pull_legs', 'Push Pull Legs'), ('bro_split', 'Bro Split'), ('hybrid', 'Hybrid')], max_length=50)),
                ('shared_days', models.JSONField(default=list)),
                ('plan_json', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('buddy_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='buddy.buddypair')),
                ('selected_gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='gyms.gym')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExercisePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performed_weight', models.FloatField()),
                ('performed_reps', models.PositiveIntegerField()),
                ('rir', models.PositiveIntegerField(help_text='Reps in reserve')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='workouts.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_performances', to=settings.AUTH_USER_MODEL)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='workouts.sharedworkoutplan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
