# Generated by Django 5.2.14 on 2026-05-18 19:06

import common.validators.injury_tags
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='movement_tags',
            field=models.JSONField(default=list, validators=[common.validators.injury_tags.validate_injury_tags]),
        ),
    ]
